/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.rizzo.tictactoe;

import com.rizzo.tictactoe.CellStates;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * The main containin the cells that let you play Tic Tac Toe.
 * @author Simone
 */
public class TTTBoard extends javax.swing.JFrame implements PropertyChangeListener {

    private List<TTTCell> cellsGrid;
    private int cellnum=9;
    private final PropertyChangeSupport prpCngSpp = new PropertyChangeSupport(this);
    
    /**
     * Creates new form TTTBoard
     */
    public TTTBoard() {
        initComponents();
        initCellsGrid();
    }
    
    public void addPropChangeListener(PropertyChangeListener listner){
        prpCngSpp.addPropertyChangeListener(listner);
    }
    
    /**
     * We initialize the grid and assign the listner between:
     * Board -> cells: for the end game conditions.
     * cells -> Board: for the varius action.
     * Board -> controller: for the end game conditios.
     */
    public void initCellsGrid(){
        // insert all cells inside a datastructure
        this.cellsGrid = new ArrayList<>();
        this.cellsGrid.add(cell00);
        this.cellsGrid.add(cell01);
        this.cellsGrid.add(cell02);
        this.cellsGrid.add(cell10);
        this.cellsGrid.add(cell11);
        this.cellsGrid.add(cell12);
        this.cellsGrid.add(cell20);
        this.cellsGrid.add(cell21);
        this.cellsGrid.add(cell22);
        
        int i=0;
        // attach for each cell the controller listener
        for(TTTCell c:this.cellsGrid){
            c.addVetoChangeListener(this.controller);
            this.addPropChangeListener(c);
            c.addPropChangeListener(this);
            this.addPropChangeListener(this.controller);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        restartButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rizzo TIC-TAC-TOE");

        restartButton.setBackground(new java.awt.Color(255, 0, 51));
        restartButton.setText("RESTART");
        restartButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addComponent(restartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Reset button pressed reinitialize the game from the beginning.
     * @param evt 
     */
    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        // TODO add your handling code here:
        this.cellnum=9;
        prpCngSpp.firePropertyChange("reset", null, null);
    }//GEN-LAST:event_restartButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTTBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTTBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTTBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTTBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TTTBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton restartButton;
    // End of variables declaration//GEN-END:variables

    /**
     * We compute if the game is ended by evidencing the tris.
     * @param evt event launched from the cells.
     */
    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        cellnum-=1;
        Optional<List<TTTCell>> cells = isGameEnded();
        if(cells.isPresent()){
            CellStates the_winner_is = cells.get().get(0).getCellState();
            prpCngSpp.firePropertyChange("win", null, cells.get()); //we fire that the game is ended with the list of cells.
            prpCngSpp.firePropertyChange("winner_is", null, the_winner_is); //we fire that the game is ended with the winner X/O.
        }
        else if(cellnum==0){ //if we have used all the cells and no one have won the conclusion is a draw.
            prpCngSpp.firePropertyChange("draw", null, null);
        } 
    }
    /**
     * Checks if a triple of cells given as parameters have the same state.
     * @param winningcells
     * @param c1
     * @param c2
     * @param c3
     * @return a list of winning cells if true otherwise empty list.
     */
    public List<TTTCell> checkIfEqual(List winningcells, TTTCell c1, TTTCell c2,TTTCell c3){        
        if(c1.getCellState() != CellStates.INIT && c1.getCellState() == c2.getCellState() && c2.getCellState()  == c3.getCellState()){
            winningcells.add(c3);
            winningcells.add(c2);
            winningcells.add(c1);
            return winningcells;
        }
        return winningcells;
    }
    /**
     * Checks if the game is ended by controlling all the cases.
     * @return the list of the winning cells otherwise empty optional.
     */
    private Optional<List<TTTCell>> isGameEnded(){
        List<TTTCell> winningcells = new ArrayList<>();
        winningcells = checkIfEqual(winningcells,cellsGrid.get(0),cellsGrid.get(1),cellsGrid.get(2));
        winningcells = checkIfEqual(winningcells,cellsGrid.get(3),cellsGrid.get(4),cellsGrid.get(5));
        winningcells = checkIfEqual(winningcells,cellsGrid.get(6),cellsGrid.get(7),cellsGrid.get(8));
        winningcells = checkIfEqual(winningcells,cellsGrid.get(0),cellsGrid.get(3),cellsGrid.get(6));
        winningcells = checkIfEqual(winningcells,cellsGrid.get(1),cellsGrid.get(4),cellsGrid.get(7));
        winningcells = checkIfEqual(winningcells,cellsGrid.get(2),cellsGrid.get(5),cellsGrid.get(8));
        winningcells = checkIfEqual(winningcells,cellsGrid.get(0),cellsGrid.get(4),cellsGrid.get(8));
        winningcells = checkIfEqual(winningcells,cellsGrid.get(6),cellsGrid.get(4),cellsGrid.get(2));
        if(winningcells.size()>0)
            return Optional.of(winningcells);
        else return Optional.empty();
    }
}
